Feature/get mappings
ttab/elephant-index pull request #139
Opened 2024-11-05 15:03 UTC by hugowetterberg

Makes it possible for clients (and developers) to inspect what the documents get mapped to in Open Search. The `type` is mostly the same as the actual OS type for the property, but the goal is to expose the "logical" type, not details about the OS implementation. That's why the actual mapping:

``` json
  "document.title": {
    "type": "text",
    "fields": {
      "prefix": {
        "type": "text",
        "analyzer": "elephant_prefix_analyzer",
        "search_analyzer": "elephant_prefix_search_analyzer"
      }
    }
  },
```

Gets translated to:

```
    {
      "name": "document.title",
      "type": "text",
      "fields": [
        {
          "name": "prefix",
          "type": "prefix"
        }
      ]
    },
```

I plan to follow this up with a second PR that a) changes the indexer so that all the properties that have been `keyword` use the `icu_collation_keyword` type instead. When that happens I think that they just should be reported as `keyword`, as that's what they are, they're just in the language one would expect from the document language.

2024-11-05 15:05 UTC, hugowetterberg commented
Implementation of https://github.com/ttab/elephant-api/pull/20

2024-11-06 12:10 UTC, hugowetterberg commented
I added the icu-change to this PR, dealing with chained PR:s is so messy.

2024-11-06 12:12 UTC, hugowetterberg commented
The individual changesets are still readable in atomic commits https://github.com/ttab/elephant-index/pull/139/commits/fd7e41fe778a8f0cebbec1ff1b8551bd03041587 (GetMappingSource) and https://github.com/ttab/elephant-index/pull/139/commits/a9f09b96ee653b25e0c910e4929deebcb48dbfbd (use icu_collation_keyword),

2024-11-07 08:34 UTC, danijelvukoje requested changes

2024-11-07 08:34 UTC, danijelvukoje commented on index/server.go
>  	seachAPI := index.NewSearchV1Server(
Typo? `searchAPI`

2024-11-07 08:34 UTC, danijelvukoje commented on index/search_api.go
> +	auth, err := RequireAnyScope(ctx, ScopeSeach, ScopeIndexAdmin)
Typo? `ScopeSearch`

2024-11-07 13:04 UTC, danijelvukoje approved these changes
Sweet! 🙂

2024-11-07 13:05 UTC, merged